# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

#os:
#  - linux
#  - osx

julia:
  #- 1.1  # FIXME: currently crashes during GC in MPtrMarkFunc
  - 1.2
  - 1.3
  - nightly

# for GAP.jl (until we have a binary builder for it)
addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev
env:
  global:
    - GAP_INSTALL_PACKAGES=minimal

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

codecov: true
coveralls: true
